import { Button } from "@/components/ui/button";

import dynamic from "next/dynamic";
import Link from "next/link";
import { Redo } from "lucide-react";
import ImagesAbout from "../components/ImagesAbout";
import { Metadata } from "next";

const MotionLeft = dynamic(() => import("@/components/animations/MotionLeft"), {
  ssr: false,
});

export const metadata: Metadata = {
  title: "About Us",
  description: "Generated by create next app",
};

const AboutSection = () => {
  return (
    <section
      className="text-center mt-20 pt-20 mx-auto bg-secondary"
      id="about"
    >
      <div className="container relative w-full flex flex-col md:flex-row justify-center md:justify-between  items-center md:items-start xl:items-center  gap-20">
        <MotionLeft className="w-full md:w-1/2 flex flex-col gap-4">
          <div className="flex flex-col gap-y-4">
            <p className="text-xl uppercase text-shadow-primary">About Us</p>
            <h2 className="text-xl lg:text-4xl font-bold">
              Real Estate CONT. L.L.C
            </h2>

            <p className="mx-auto text-sm lg:text-lg">
              HAMBOOS CONT. L.L.C is a leading U.A.E based contractor since
              1984, we introduce high level engineering solutions specializing
              in Concrete structures as well as Cold Formed Steel Structures,
              M.E.P Services and residential and commercial construction.
              HAMBOOS CONT.
            </p>
          </div>

          <div>
            <div className="flex items-center justify-center gap-x-1">
              <h3 className="text-lg">Call Us Now</h3>
              <Redo size={20} className="rotate-90 mt-3 text-primary" />
            </div>
            <Link href="tel:+971508577859">
              <Button variant={"link"}>+971508577859</Button>
            </Link>
          </div>
          <Button className="block mx-auto">Send Massage</Button>
        </MotionLeft>

        <ImagesAbout />
      </div>
    </section>
  );
};

export default AboutSection;
