import { Button } from "@/components/ui/button";
import React from "react";
import dynamic from "next/dynamic";
import * as LucideIcons from "lucide-react";
import { FeaturesItems } from "@/constants";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Features",
  description: "Generated by create next app",
};

const MotionLeft = dynamic(() => import("@/components/animations/MotionLeft"), {
  ssr: true,
});
const MotionRight = dynamic(
  () => import("@/components/animations/MotionRight"),
  {
    ssr: true,
  }
);
const MotionDown = dynamic(() => import("@/components/animations/MotionDown"), {
  ssr: true,
});
const MotionUp = dynamic(() => import("@/components/animations/MotionUp"), {
  ssr: true,
});

const motionComponents: Record<string, React.ElementType> = {
  MotionLeft,
  MotionRight,
  MotionDown,
  MotionUp,
};

const Features = () => {
  return (
    <section className="overflow-hidden py-24" id="features">
      <h1 className="section-title">
        Features
      </h1>

      <div className="container relative  mx-auto">
        <div className="grid md:grid-cols-2 xl:grid-cols-3 items-center justify-center">
          {FeaturesItems.map(
            ({ motion, icon, title, description, subDescription }, indx) => {
              const Icon = LucideIcons[
                icon as keyof typeof LucideIcons
              ] as React.ElementType;
              const MotionComponent = motionComponents[motion];
              return (
                MotionComponent && (
                  <MotionComponent key={indx} className="py-4 px-3">
                    <div className="bg-secondary md:h-48 border border-primary p-6 rounded-lg duration-300 group hover:bg-primary/70">
                      <div className="flex items-center gap-3">
                        <div className="w-fit h-fit p-2 inline-flex items-center justify-center rounded-full bg-card duration-500 group-hover:bg-secondary border border-primary text-primary mb-4">
                          {Icon && (
                            <Icon
                              className="duration-500 group-hover:rotate-[360deg]"
                              size={35}
                            />
                          )}
                        </div>
                        <h2 className="text-lg font-medium mb-2">{title}</h2>
                      </div>
                      <p className="leading-relaxed text-sm">
                        {description}
                        <span className="mr-1 text-primary font-medium duration-500 group-hover:text-secondary">
                          {subDescription}
                        </span>
                      </p>
                    </div>
                  </MotionComponent>
                )
              );
            }
          )}
        </div>

        <MotionUp className="flex justify-center mt-5">
          <Button variant={"outline"}>Add a Listing</Button>
        </MotionUp>
      </div>
    </section>
  );
};

export default Features;
